### ISSUE TITLE
Orbus OTM translator

### ISSUE THREAD

**Issue by rakkhi** [iriusrisk/startleft#279]
Hi, we are just putting in https://www.orbussoftware.com/solutions/enterprise-architecture for our solution architecture modelling. Also considering Iriusrisk for cyber security threat modelling. Does anyone have an existing OTM translator for this?

**Comment by daFont-iriusrisk** [comment]
Hi @rakkhi,

Unfortunately, we do not plan to implement an Orbus solution in the short term, 

Anyway we have available in our documentation a guide to build new processors https://iriusrisk.github.io/startleft/development/Create-a-new-StartLeft-Processor if you decide to start your own implementation and need to solve any doubt we are here to help, feel free to contact us.

Thank you for your interest in the project.
